# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "d40904bf2607e167074923a5c2e04657e6f3860d"

[[deps.SteinVariational]]
path = "."
uuid = "9d6f0553-efb5-457e-8578-4a50808cb26d"
version = "1.0.0-DEV"
