name = "SteinVariational"
uuid = "9d6f0553-efb5-457e-8578-4a50808cb26d"
authors = ["Andreas Scheidegger"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
